FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
        bc \
        bison \
        build-essential \
        cpio \
        flex \
        libelf-dev \
        libncurses-dev \
        libssl-dev \
        vim-tiny 


RUN apt-get install -y \
        libncurses-dev \
        gawk \
        flex bison \
        openssl \
        libssl-dev \
        dkms \
        libelf-dev \
        libudev-dev \
        libpci-dev \
        libiberty-dev \
        autoconf \
        llvm \
        dwarves 

RUN apt-get install -y liblz4-tool

WORKDIR /root/mtp
