#!/bin/bash
#echo "" > ./source/mtpfiles.rst
#echo ".. toctree:: " >> ./source/mtpfiles.rst
#echo "     :maxdepth: 2 " >> ./source/mtpfiles.rst
#echo "     :caption: Contents:"  >> ./source/mtpfiles.rst
#echo "" >> ./source/mtpfiles.rst

for file in /home/kerneldev/mtp/linux-6.6.2/net/mtp/*.c
do
    if [[ "$file" == *".mod."* ]]; then
        echo "$file file has more than one dots, hence autogenerated"
    else 
        name=${file##*/}
        base=${name%.txt}
        ./scripts/kernel-doc -rst -no-doc-sections "$file" > ./source/mtpfiles/"${base}.rst"
    #    echo "  ${base}.rst" >> ./source/mtpfiles.rst
    fi
done